language: python
python:
- 3.5
- 3.6
install:
- pip install pipenv
- pipenv install
script:
- pipenv run ./manage.py migrate
- pipenv run ./manage.py compilescss
- pipenv run ./manage.py collectstatic --no-input
- pipenv run ./manage.py test
env:
- TRAVIS=true
