name: "E2E and accessibility tests"

on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Run end-to-end accessibility tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r tests/requirements.txt

      - name: Install Playwright browsers
        run: |
          python -m playwright install --with-deps chromium

      - name: Build site (Lektor)
        run: |
          cd PyBay
          lektor build -f webpack -O ../_site

      - name: Run tests
        env:
          PLAYWRIGHT_HEADLESS: "1"
        run: |
          pytest -q tests/test_server.py
