name: "E2E and accessibility tests"

on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Run end-to-end accessibility tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip
          cache-dependency-path: tests/requirements.txt

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r tests/requirements.txt

      - name: Install Playwright browsers
        run: |
          python -m playwright install --with-deps chromium

      - name: Run E2E a11y tests against built pages
        env:
          PLAYWRIGHT_HEADLESS: "1"
        run: |
          pytest tests/test_server.py --maxfail=1 --disable-warnings
